config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  get "u/:username" => "public#profile", as: :profile

  resources :communities do
    resources :posts
  end

  resources :subscriptions
  resources :comments, only: [:create]

  post "posts/vote" => "votes#create"

  root to: "public#index"
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :communities, through: :subscriptions
  has_many :posts
  has_many :comments
  has_many :votes

  validates_presence_of :first_name, :last_name, :username

  def full_name
    "#{first_name} #{last_name}"
  end

  def upvoted_post_ids
    votes.where(upvote: true).pluck(:post_id)
  end

  def downvoted_post_ids
    votes.where(upvote: false).pluck(:post_id)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :account

  validates_presence_of :message, :account_id, :post_id
end

app/models/community.rb
class Community < ApplicationRecord
  belongs_to :account
  validates_presence_of :name, :url, :rules
  has_many :posts
  has_many :subscriptions
  has_many :subscribers, through: :subscriptions, source: :account
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :account
  belongs_to :community
  validates_presence_of :title, :body, :account_id, :community_id

  has_many :comments
  has_many :votes

  def score
    self.upvotes - self.downvotes
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :account
  belongs_to :community
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :account
  belongs_to :post

  POST_VOTE_KARMA = 2

  # Each account can only make 1 vote to a post
  validates_uniqueness_of :account_id, scope: :post_id

  after_create :increment_vote, :increase_karma
  after_destroy :decrement_vote, :decrease_karma

  private

  def increment_vote
    field = self.upvote ? :upvotes : :downvotes
    Post.find(self.post_id).increment(field).save
  end

  def decrement_vote
    field = self.upvote ? :upvotes : :downvotes
    Post.find(self.post_id).decrement(field).save
  end

  def increase_karma
    account = Account.find(self.account_id)
    account.increment(:karma, POST_VOTE_KARMA).save
  end

  def decrease_karma
    account = Account.find(self.account_id)
    account.decrement(:karma, POST_VOTE_KARMA).save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new comment_params
    @comment.account_id = current_account.id

    respond_to do |format|
      format.js {
        if @comment.save
          @comments = Comment.where(post_id: @comment.post_id)
          render "comments/create"
        else
          #TODO: unable to save
        end
      }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:message, :post_id)
  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :authenticate_account!, except: [:index, :show]
  before_action :set_community, only: [:show]

  def index
    @communities = Community.all
  end

  def show
    @posts = @community.posts.sort_by(&:score).reverse
    @subscriber_count = @community.subscribers.count
    @is_subscribed = account_signed_in? ? Subscription.where(community_id: @community.id, account_id: current_account.id).any? : false
    @subscription = Subscription.new
  end

  def new
    @community = Community.new
  end

  def create
    @community = Community.new community_params
    @community.account_id = current_account.id

    if @community.save
      redirect_to communities_path
    else
      render :new
    end
  end

  private

  def set_community
    @community = Community.find(params[:id])
  end

  def community_params
    params.require(:community).permit(:name, :url, :summary, :rules)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_account!, except: [:index, :show]
  before_action :auth_subscriber, only: [:new]

  def index
    redirect_to community_path(params[:community_id])
  end

  def show
    @community = Community.find(params[:community_id])
    @post = Post.includes(:comments).find(params[:id])
    @comment = Comment.new
  end

  def new
    @community = Community.find(params[:community_id])
    @post = Post.new
  end

  def create
    @community = Community.find(params[:community_id])
    @post = @community.posts.create(post_params)
    @post.account_id = current_account.id

    if @post.save
      redirect_to community_path(@community)
    else
      render :new
    end
  end

  private

  def auth_subscriber
    unless Subscription.where(community_id: params[:community_id], account_id: current_account.id).any?
      redirect_to community_path(params[:community_id]), flash: { danger: "You are not authorized to view this page" }
    end
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def index
    @communities = Community.all.limit(5)
    @posts = Post.limit(20).sort_by(&:score).reverse
  end

  def profile
    @profile = Account.find_by_username params[:username]
    @posts = Post.where account_id: @profile.id
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def create
    @subscription = Subscription.new(subscription_params)
    @subscription.account_id = current_account.id
    @subscription.save

    redirect_to community_path(@subscription.community_id)
  end

  private

  def subscription_params
    params.require(:subscription).permit(:community_id)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_account!

  def create
    post_id = params[:post_id]
    vote = Vote.new
    vote.post_id = post_id
    vote.upvote = params[:upvote]
    vote.account_id = current_account.id

    # check if vote by this exists
    existing_vote = Vote.where(account_id: current_account.id, post_id: post_id)

    respond_to do |format|
      format.js {
        if existing_vote.size.positive?
          # destroy existing vote
          existing_vote.first.destroy
        else
          @success = vote.save
        end

        @post = Post.find(post_id)
        @is_upvote = params[:upvote] == 'true'

        render 'votes/create'
      }
    end
  end

  private

  def vote_params
    params.require(:vote).permit(:upvote, :post_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/votes_helper.rb
module VotesHelper
  def is_upvoted post
    account_signed_in? && current_account.upvoted_post_ids.include?(post.id)
  end

  def is_downvoted post
    account_signed_in? && current_account.downvoted_post_ids.include?(post.id)
  end
end

app/views/comments/create.js.erb
console.log("comment created...")

document.getElementById("post-comments").innerHTML = "<%= escape_javascript(render partial: 'posts/comments', locals: {comments: @comments}) %>"

document.getElementById("comment_message").value = "";
console.log(document.getElementById("comment_message"))

app/views/communities/_form.html.erb
<div class="row">
  <div class="col-sm-6">
    <%= form_for @community do |form| %>
      <div class="form-group">
        <%= label_tag :name %>
        <%= form.text_field :name, class: "form-control" %>
        <% @community.errors.full_messages_for(:name).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>

      <div class="form-group">
        <%= label_tag :url %>
        <%= form.text_field :url, class: "form-control" %>
        <% @community.errors.full_messages_for(:url).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>

      <div class="form-group">
        <%= label_tag :summary %>
        <%= form.text_field :summary, class: "form-control" %>
        <% @community.errors.full_messages_for(:summary).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>

      <div class="form-group">
        <%= label_tag :rules %>
        <%= form.text_area :rules, class: "form-control" %>
        <% @community.errors.full_messages_for(:rules).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>

      <%= form.submit "Create", class: "btn btn-primary mt-4" %>
    <% end %>
  </div>
</div>

app/views/communities/_subscribe.html.erb
<%= form_for @subscription do |f| %>
  <%= f.hidden_field :community_id, value: community_id %>
  <%= f.submit "Join Community", class: "btn btn-success text-uppercase" %>
<% end %>

app/views/communities/index.html.erb
<% if account_signed_in? %>
  <div class="float-end">
    <%= link_to "Create New Community", new_community_path, class: "btn btn-outline-primary" %>
  </div>
<% end %>

<% if @communities.size > 0 %>
  <% @communities.each do |community| %>
    <div class="card">
      <h3><%= link_to community.name, community %></h3>
      <%= simple_format community.rules %>
    </div>
  <% end %>
<% else %>
  <p>No communities to display.</p>
<% end %>

app/views/communities/new.html.erb
<h2>New Community</h2>

<%= render partial: "form" %>

app/views/communities/show.html.erb
<script type="text/javascript" charset="utf-8">
  document.title = "r/<%= @community.name %> | Reddit Clone"
</script>

<div class="row">
  <div class="col-sm-8">
    <h3 class="fw-bold mb-4">r/<%= @community.name %></h3>
  </div>
  <div class="col-sm-4 text-end">
    <% if @is_subscribed %>
      <%= link_to "Create New Post", new_community_post_path(@community), class: "btn btn-primary" %>
    <% else %>
      <%= render partial: "communities/subscribe", locals: { community_id: @community.id } %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-sm-8">
    <%= render partial: "posts/list", locals: { posts: @posts } %>
  </div>
  <div class="col-sm-4">
    <div class="card p-3">
      <h4>About this community</h4>
      <p class="mt-2 mb-3"><%= @community.summary %></p>
      <p><%= pluralize @subscriber_count, "member" %></p>
      <small>
        <%= simple_format @community.rules %>
      </small>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
footer

app/views/layouts/_header.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 d-flex align-items-center border-bottom py-3">
      <p class="flex-grow-1 h3">
        <%= link_to "Reddit Clone", root_path, class: "text-decoration-none" %>
      </p>
      <div class="d-flex flex-row align-items-center">
        <% if account_signed_in? %>
          <div class="karma me-2">
            <%= current_account.karma %>
            <span class="fa fa-star text-warning"></span>
          </div>
          <div class="dropdown show">
            <a class="btn btn-white dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-bs-toggle="dropdown">
              <%= current_account.full_name %>
            </a>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <%= link_to "Profile", profile_path(current_account.username), class: "dropdown-item" %>
              <%= link_to "Settings", edit_account_registration_path, class: "dropdown-item" %>
              <%= link_to "Sign Out", destroy_account_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </div>
        <% else %>
          <%= link_to "Log In", new_account_session_path, class: "btn btn-outline-primary" %>
          <%= link_to "Sign Up", new_account_registration_path, class: "btn btn-outline-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails Reddit Clone</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render partial: "layouts/header" %>

<% flash.each do |key, value| %>
  <div class="alert <%= key == 'alert' ? 'alert-danger' : 'alert-info' %> alert-dismissible fade show" role="alert">
    <%= value %>
    <button
      type="button"
      class="float-right btn-close"
      data-dismiss="alert"
      aria-label="Close"
      onclick="$('.alert').alert('close')"
    >
    </button>
  </div>
<% end %>


<section class="bg-light">
  <div class="container py-4">
    <div class="row">
      <div class="col-sm-12">
        <%= yield %>
      </div>
    </div>
  </div>
</section>

<%= render partial: "layouts/footer" %>
</body>
</html>

app/views/posts/_comments.html.erb
<% if comments.length > 0 %>
  <% comments.each do |comment| %>
    <div class="card p-2 mb-1">
      <%= link_to comment.account.full_name, profile_path(comment.account.username), class: "text-decoration-none" %>
      <p class="mt-1 mb-0"><%= comment.message %></p>
    </div>
  <% end %>
<% end %>

app/views/posts/_form.html.erb
<div class="row">
  <div class="col-sm-6">
    <%= form_for [@community, @post] do |form| %>
      <div class="form-group">
        <%= label_tag :title %>
        <%= form.text_field :title, class: "form-control" %>
        <% @post.errors.full_messages_for(:title).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>

      <div class="form-group">
        <%= label_tag :body %>
        <%= form.text_area :body, class: "form-control" %>
        <% @post.errors.full_messages_for(:body).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>

      <%= form.submit "Create Post", class: "btn btn-primary mt-4" %>
    <% end %>
  </div>
</div>

app/views/posts/_list.html.erb
<% @posts.each do |post| %>
  <div class="card p-3 mb-2">
    <div class="row">
      <div class="col-1">
        <%= render partial: "votes/vote_block", locals: { post: post } %>
      </div>
      <div class="col-11">
        <h4>
          <%= link_to post.title, community_post_path(post.community_id, post), class: "text-decoration-none" %>
        </h4>
        <small class="mb-2">
          <%= link_to "r/#{post.community.name}", post.community %> Posted
          by <%= link_to post.account.full_name, profile_path(post.account.username) %> <%= time_ago_in_words post.created_at %>
        </small>
        <p><%= truncate post.body, length: 200 %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render partial: "form" %>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render partial: "form" %>

app/views/posts/show.html.erb
<script type="text/javascript" charset="utf-8">
    document.title = "<%= @post.title %> | Reddit Clone"
</script>

<div class="row">
  <div class="col-1">
    <%= render partial: "votes/vote_block", locals: { post: @post } %>
  </div>
  <div class="col-11">
    <h2><%= @post.title %></h2>

    <p><%= simple_format @post.body %></p>
  </div>
</div>

<h5>Leave a comment</h5>

<div id="post-comments">
  <%= render partial: "posts/comments", locals: { comments: @post.comments } %>
</div>

<%= form_for @comment, remote: true do |f| %>
  <%= f.hidden_field :post_id, value: @post.id %>
  <%= f.text_area :message, placeholder: "Your comment goes here...", class: "form-control" %>
  <%= f.submit "Submit comment", class: "btn btn-success mt-2" %>
<% end %>

app/views/votes/_vote_block.html.erb
<div class="d-flex flex-column align-items-center pt-1 vote"
     id="vote-actions-<%= post.id %>"
     data-id="<%= post.id %>">
  <span id="upvote-<%= post.id %>"
        class="fa fa-arrow-up upvote <%= is_upvoted(post) ? 'active' : '' %>"></span>
  <span class="my-1 vote-score"><%= post.score %></span>
  <span id="downvote-<%= post.id %>"
        class="fa fa-arrow-down downvote <%= is_downvoted(post) ? 'active' : '' %>"></span>
</div>

app/views/votes/create.js.erb
// update total votes on view for post
$("#vote-actions-<%= @post.id %> .vote-score").text("<%= @post.score %>")

// update color of vote buttons
<% if account_signed_in? %>
  <% if is_upvoted @post %>
    $("#upvote-<%= @post.id %>").addClass("active")
    $("#downvote-<%= @post.id %>").removeClass("active")
  <% elsif is_downvoted @post %>
    $("#upvote-<%= @post.id %>").removeClass("active")
    $("#downvote-<%= @post.id %>").addClass("active")
  <% else %>
    $("#upvote-<%= @post.id %>").removeClass("active")
    $("#downvote-<%= @post.id %>").removeClass("active")
  <% end %>
<% end %>